### ISSUE TITLE
Write the global attribute handler for specific AMF products

### ISSUE THREAD

**Issue by agstephens** [ncasuk/amf-check-writer#29]
@gapintheclouds this may overlap with an existing github Issue but just creating it as a reminder to pick up.

**Comment by gapintheclouds** [comment]
Hi @agstephens ,

On the topic of integrating specific global attribute checks.

I've been trying to work out whether we can/should use the existing ```GlobalAttrCheck``` which is used for the overall global attributes instead of creating a separate ```GlobalAttributesCV```. This would be useful to only have one global attribute check creator that can do both the overall and specific global attributes. And then we can access the regex expressions in ```GlobalAttrCheck```. What do you think?

I've been playing with it a bit but wanted to check before I went into the depths.

**Comment by gapintheclouds** [comment]
@agstephens Think I've sorted it now.
